consul:
    image: qnib/consul
    ports:
     - "8500:8500"
    hostname: consul
    dns: 127.0.0.1
    privileged: true

mongodb:
    image: qnib/mongodb
    dns: 127.0.0.1
    hostname: mongodb
    ports:
     - "27017:27017"
     - "28017:28017"
    links:
     - consul:consul
    privileged: true

rocketchat:
    image: qnib/rocketchat:node
    dns: 127.0.0.1
    hostname: rocketchat
    ports:
     - "3000:3000"
    links:
     - consul:consul
     - mongodb:db
    privileged: true
